package com.maswadkar.developers.androidify.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (Fallback for Android < 12)
val md_theme_light_primary = Color(0xFF2E7D32)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA5D6A7)
val md_theme_light_onPrimaryContainer = Color(0xFF1B5E20)
val md_theme_light_secondary = Color(0xFF558B2F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC5E1A5)
val md_theme_light_onSecondaryContainer = Color(0xFF33691E)
val md_theme_light_tertiary = Color(0xFF00796B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF80CBC4)
val md_theme_light_onTertiaryContainer = Color(0xFF004D40)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFDFDF5)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFDFDF5)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF44483E)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_outlineVariant = Color(0xFFC4C8BA)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
val md_theme_light_inversePrimary = Color(0xFF81C784)

// Dark Theme Colors (Fallback for Android < 12)
val md_theme_dark_primary = Color(0xFF81C784)
val md_theme_dark_onPrimary = Color(0xFF1B5E20)
val md_theme_dark_primaryContainer = Color(0xFF2E7D32)
val md_theme_dark_onPrimaryContainer = Color(0xFFA5D6A7)
val md_theme_dark_secondary = Color(0xFFAED581)
val md_theme_dark_onSecondary = Color(0xFF33691E)
val md_theme_dark_secondaryContainer = Color(0xFF558B2F)
val md_theme_dark_onSecondaryContainer = Color(0xFFC5E1A5)
val md_theme_dark_tertiary = Color(0xFF4DB6AC)
val md_theme_dark_onTertiary = Color(0xFF004D40)
val md_theme_dark_tertiaryContainer = Color(0xFF00796B)
val md_theme_dark_onTertiaryContainer = Color(0xFF80CBC4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE3E3DC)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE3E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF44483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BA)
val md_theme_dark_outline = Color(0xFF8E9285)
val md_theme_dark_outlineVariant = Color(0xFF44483E)
val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
val md_theme_dark_inverseOnSurface = Color(0xFF2F312D)
val md_theme_dark_inversePrimary = Color(0xFF2E7D32)

// Chat bubble colors
val UserBubbleLight = Color(0xFFDCEDC8)
val UserBubbleDark = Color(0xFF33691E)
val ModelBubbleLight = Color(0xFFF5F5F5)
val ModelBubbleDark = Color(0xFF2D2D2D)

